include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 120
  trailing_commas: preserve

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.mappable.dart"

linter:
  rules:
    public_member_api_docs: false
