include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.mappable.dart"

linter:
  rules:
    public_member_api_docs: false
