name: gifter
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  auto_route: ^10.2.0
  dart_mappable: ^4.6.1
  flutter: { sdk: flutter }
  flutter_riverpod: ^3.0.3
  pocketbase: ^0.23.0+1
  riverpod_annotation: ^3.0.3
  shadcn_ui: ^0.38.4

dev_dependencies:
  auto_route_generator: ^10.2.5
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  dart_mappable_builder: ^4.6.0
  flutter_lints: ^6.0.0
  flutter_test: { sdk: flutter }
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  very_good_analysis: ^10.0.0

flutter: { uses-material-design: false }
